ExtraHop: Feature - PAPP-26197: Python conversion
splunk-soar-connectors/extrahop pull request #2
Opened 2022-07-15 06:06 UTC by ighelani-crest

## Pull Request Checklist

#### Please check if your PR fulfills the following requirements:
- [ ] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
## Pull Request Type

#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [x] Feature (Python3 conversion)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

2022-08-22 13:52 UTC, dhwanis-crest commented
The MR will be merged once all the pipeline passes and all the dependencies are merged (asset and playbooks) and the pipeline passes successfully.

2022-08-24 23:45 UTC, splunk-jessica commented on readme.html
> +	<p>The Extrahop and Splunk SOAR connect through simple, powerful REST APIs, making it easy to build and iterate new use cases to get the most value for the least effort, a vital capability for thinl
```suggestion
	<p>Extrahop and Splunk SOAR connect through simple, powerful REST APIs, making it easy to build and iterate new use cases to get the most value for the least effort, a vital capability for thinly stretched enterprise security teams.</p>
</body>
```

2022-08-24 23:45 UTC, splunk-jessica commented on extrahop.json
> +            "description": "Get a list of peers that a device communicated within the last N minutes",
```suggestion
            "description": "Get a list of peers that a device communicated with within the last N minutes",
```

2022-08-24 23:45 UTC, splunk-jessica commented on extrahop.json
> +            "verbose": "This action retrieves a list of all of the peers that a device communicated within the last N minutes, optionally filtered by role and/or protocol. Either 'ip' or 'eh_api_id'
```suggestion
            "verbose": "This action retrieves a list of all of the peers that a device communicated with within the last N minutes, optionally filtered by role and/or protocol. Either 'ip' or 'eh_api_id' parameter is required. If both the parameters are provided, 'eh_api_id' will be considered.",
 ```

2022-08-25 08:01 UTC, dhwanis-crest commented on extrahop.json
> +            "verbose": "This action retrieves a list of all of the peers that a device communicated within the last N minutes, optionally filtered by role and/or protocol. Either 'ip' or 'eh_api_id'
Done

2022-08-25 08:01 UTC, dhwanis-crest commented on extrahop.json
> +            "description": "Get a list of peers that a device communicated within the last N minutes",
Done

2022-08-25 08:01 UTC, dhwanis-crest commented on readme.html
> +	<p>The Extrahop and Splunk SOAR connect through simple, powerful REST APIs, making it easy to build and iterate new use cases to get the most value for the least effort, a vital capability for thinl
Done

2022-08-25 15:18 UTC, dhwanis-crest commented
The sanity test pipeline fails because it expects https://us-west-2.console.aws.amazon.com/codesuite/codebuild/875003031410/projects/sanity-tests/batch/sanity-tests%3Ac2c60291-2133-4db9-a366-bc42b433c933/env_var?region=us-west-2 the pytest of the app in main branch (which is not yet merged in main) whereas the integration test pipeline passes as it is able to find pytest with the same name as app branch name - https://us-west-2.console.aws.amazon.com/codesuite/codebuild/875003031410/projects/app-integration-tests/build/app-integration-tests%3A15855e86-69c9-4107-85e6-8bacbb288505/env_var?region=us-west-2

2022-08-25 20:48 UTC, tonyc-phantom requested changes

2022-08-25 20:48 UTC, tonyc-phantom commented on extrahop.json
> +                    "description": "Comma separated IP addresses",
This should be 'Comma-separated'

2022-08-26 07:19 UTC, dhwanis-crest commented on extrahop.json
> +                    "description": "Comma separated IP addresses",
Done

2022-08-26 15:42 UTC, tonyc-phantom approved these changes

2022-08-26 21:40 UTC, splunk-jessica approved these changes

2022-08-29 05:52 UTC, merged